#!/usr/bin/env bash
#
# install-hooks.sh — wire up local git hooks for mesh-common after a fresh
# clone. We do NOT use husky (extra dep tail); we drop a small file into
# .git/hooks/pre-commit that runs the docs-drift check.
#
# Idempotent — running again replaces the hook with the latest version.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK="$ROOT/.git/hooks/pre-commit"

if [ ! -d "$ROOT/.git" ]; then
  echo "[install-hooks] $ROOT is not a git repo; skipping" >&2
  exit 0
fi

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Generated by mesh-common/scripts/install-hooks.sh — do not hand-edit.
# Gate: every new src/index.ts export must land with README + CHANGELOG updates.
set -e
ROOT="$(git rev-parse --show-toplevel)"
exec "$ROOT/scripts/check-docs-updated.sh" --staged
EOF
chmod +x "$HOOK"

echo "[install-hooks] installed $HOOK"
echo "[install-hooks] run \`scripts/check-docs-updated.sh\` manually any time."
